name: 'Master Push'
on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Building and Publishing'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: npm install
        run: npm install

      - name: Test
        run: npm test

      - name: Publish
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > $HOME/.npmrc
          npm publish
