name: 'On Push'
on: [pull_request]

jobs:
  build:
    name: 'Testing'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: npm install
        run: npm install

      - name: Test
        run: npm test

      - name: Beta Version
        run: npm --no-git-tag-version version prerelease --preid=beta

      - name: Publish Prep
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > $HOME/.npmrc

      - name: Publish
        run: npm publish
