name: 'On Push'
on: [pull_request]

jobs:
  build:
    name: 'Testing'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - name: Test ENV
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: npm install
        run: npm install

      - name: Test
        run: npm test

      - name: Beta Version
        run: npm version prerelease --preid=beta

      - name: Publish
        run: npm publish
