name: 'Testing'
on: [push]

jobs:
  build:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          version: 10.x

      - name: npm install
        run: npm install

      - name: Test
        run: npm test
