name: 'Testing'
on: [push]

jobs:
  build:
    name: 'Testing'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - name: Test ENV
        run: echo ${{ github.sha }}

      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: npm install
        run: npm install

      - name: Test
        run: npm test
